 pipeline {                                                                                                                                                                                                                             
      agent any                                                                                                                                                                                                                          
      environment {                                                                                                                                                                                                                      
          QODANA_TOKEN = credentials('qodana-token')                                                                                                                                                                                     
      }                                                                                                                                                                                                                                  
      stages {                                                                                                                                                                                                                           
          stage('Qodana') {                                                                                                                                                                                                              
              steps {                                                                                                                                                                                                                    
                  sh 'docker run --rm -v "$WORKSPACE":/data/project -v "$WORKSPACE/qodana-results":/data/results -e QODANA_TOKEN jetbrains/qodana-js:2026.1 --save-report'                                                               
              }                                                                                                                                                                                                                          
          }                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                  
      post {                                                                                                                                                                                                                             
          always {                                                                                                                                                                                                                       
              archiveArtifacts artifacts: 'qodana-results/**', allowEmptyArchive: true                                                                                                                                                   
          }                                                                                                                                                                                                                              
      }                                                                                                                                                                                                                                  
  }
