name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run coverage

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2026.1
        env:
          QODANA_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoiR2dMNlIiLCJvcmdhbml6YXRpb24iOiJRNjlRRCIsInRva2VuIjoibmVqMDAifQ.S40ommXlvuC7iLj0Nj5B_r_DTY57h96tRM7E2FDCPFk"
          
